### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by JosieAilsa** [Benyamin428/punk-api-project#1]
### Functionality

- Another great project Ben, you’ve successfully shown all possible beers on the list, all your filters work alone and together.

### Testing

- Good to see you’ve started adding some tests, and a more tricky one on the app - obviously would like to see a few more here

### Design

- Design is neat and works well across difference device sizes
- Couple of UI suggestions to give this the extra edge - make sure your nav takes up entire vh - its looks a bit strange that it gets smaller the fewer beers you see. Also Suggest giving some kind of user feedback that you are able to scroll to see the overlapping text (if any exists) on each beer card

### Project Structure

- Make sure you are thinking in terms of container/component design patterns - all of your components are in singular folder but your CardList looks like a container to to me, and should be separate in your repo.

### React Use

- You components, functions and states are all descriptively named and neat
- You’ve shown a great understanding of React Hooks/ Lifecycle with states and useEffect used well.
- You’re API call is neat, and uses a try catch - nice work.
- We want to avoid having a large amount of state in React, so you since your filters are all related you could have made these as one lot of state stored in an object.
- Make sure your JSX is still semantic you are using a lot of `div`s instead of semantic elements. e.g there is no `nav` , `main` , `header` , `section` tags

Remember you can return from your functions early rather than using if/else - which is a bit neater. 

```jsx
const handleSearch = (event) => {
  if (event.target.value != "") {
    setSearchBeer(`beer_name=${event.target.value}`)
    return;
  };
  setSearchBeer("");
}
```

**Comment by Benyamin428** [comment]
Thank you for the feedback. I have made the following changes:

- [x] Made the navbar have a height of 100vh
- [x] Added a scrollbar for each card
- [x] Used semantic tags
- [x] Refactored my code to use component/container design pattern
- [x] Refactored functions to return earlier
